/* presets.js — Theme preset definitions */

const PRESETS = {
  midnight: {
    primary:   '#6c63ff',
    accent:    '#ff6584',
    bg:        '#0f0f17',
    surface:   '#1a1a2e',
    text:      '#e8e8f0',
    font:      "'Syne', sans-serif",
    fontSize:  16,
    radius:    12,
    shadow:    1,
    spacing:   1,
  },
  arctic: {
    primary:   '#0ea5e9',
    accent:    '#38bdf8',
    bg:        '#f0f9ff',
    surface:   '#ffffff',
    text:      '#0c1825',
    font:      "'DM Sans', sans-serif",
    fontSize:  15,
    radius:    8,
    shadow:    0,
    spacing:   1.1,
  },
  forest: {
    primary:   '#22c55e',
    accent:    '#84cc16',
    bg:        '#0a1a0f',
    surface:   '#112217',
    text:      '#d1fae5',
    font:      "'Nunito', sans-serif",
    fontSize:  16,
    radius:    16,
    shadow:    2,
    spacing:   1.1,
  },
  sunset: {
    primary:   '#f97316',
    accent:    '#ec4899',
    bg:        '#1a0a05',
    surface:   '#2a1208',
    text:      '#fff0e8',
    font:      "'Playfair Display', serif",
    fontSize:  17,
    radius:    4,
    shadow:    2,
    spacing:   1.2,
  },
  candy: {
    primary:   '#e879f9',
    accent:    '#34d399',
    bg:        '#1a0520',
    surface:   '#280830',
    text:      '#fce7ff',
    font:      "'Nunito', sans-serif",
    fontSize:  16,
    radius:    24,
    shadow:    2,
    spacing:   1,
  },
  monochrome: {
    primary:   '#e2e2e2',
    accent:    '#a0a0a0',
    bg:        '#080808',
    surface:   '#111111',
    text:      '#f5f5f5',
    font:      "'Space Mono', monospace",
    fontSize:  14,
    radius:    0,
    shadow:    0,
    spacing:   1.2,
  },
};
